// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9OnerWonLT3fL4sZ7KH_HwodYmiLkuQ8',
    appId: '1:319839114119:web:4274e68163a7932f1af922',
    messagingSenderId: '319839114119',
    projectId: 'byhandsapplication-ed36b',
    authDomain: 'byhandsapplication-ed36b.firebaseapp.com',
    storageBucket: 'byhandsapplication-ed36b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwiO419-KEP3cqlibERf1I5PgGVx4mgVM',
    appId: '1:319839114119:android:b14608aeb8e6467d1af922',
    messagingSenderId: '319839114119',
    projectId: 'byhandsapplication-ed36b',
    storageBucket: 'byhandsapplication-ed36b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8pshhvWbMwG3cthyo6Rc93TKL3oAp6Ms',
    appId: '1:319839114119:ios:4899736a5c31d7f21af922',
    messagingSenderId: '319839114119',
    projectId: 'byhandsapplication-ed36b',
    storageBucket: 'byhandsapplication-ed36b.firebasestorage.app',
    iosBundleId: 'com.example.byhands',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8pshhvWbMwG3cthyo6Rc93TKL3oAp6Ms',
    appId: '1:319839114119:ios:4899736a5c31d7f21af922',
    messagingSenderId: '319839114119',
    projectId: 'byhandsapplication-ed36b',
    storageBucket: 'byhandsapplication-ed36b.firebasestorage.app',
    iosBundleId: 'com.example.byhands',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9OnerWonLT3fL4sZ7KH_HwodYmiLkuQ8',
    appId: '1:319839114119:web:2a3e9a30eb917b3b1af922',
    messagingSenderId: '319839114119',
    projectId: 'byhandsapplication-ed36b',
    authDomain: 'byhandsapplication-ed36b.firebaseapp.com',
    storageBucket: 'byhandsapplication-ed36b.firebasestorage.app',
  );
}
